### ISSUE TITLE
nativeImage on Windows fails in 0.3.1 and 0.3.2 (No issue in 0.3.0)

### ISSUE THREAD

**Issue by Kevin-Lee** [scalameta/sbt-native-image#53]
**Describe the bug**
`nativeImage` on Windows fails in `sbt-native-image` `0.3.1` and `0.3.2` (No issue in `0.3.0`).

I'm getting the following error when running `nativeImage` on Windows platform in GitHub Actions.
https://github.com/Kevin-Lee/whatsub/runs/6899749209?check_suite_focus=true#step:7:304
```
========================================================================================================================
GraalVM Native Image: Generating 'D:\a\whatsub\whatsub\cli\target\native-image\whatsub-cli' (executable)...
========================================================================================================================
[1/7] Initializing...                                                                                    (0.0s @ 0.10GB)
Fatal error: java.lang.NoClassDefFoundError: pirate/Command
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethod(Class.java:2673)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:359)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)
Caused by: java.lang.ClassNotFoundException: pirate.Command
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 7 more
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
	at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1678)
	at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1389)
	at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1350)
	at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1337)
[error] native-image command failed with exit code '1'
[error] (cli / nativeImage) native-image command failed with exit code '1'
[error] Total time: 30 s, completed Jun 15, 2022, 12:37:27 PM
```

I get no error and build is successfully done if I use `0.3.0`.

**To Reproduce** Steps to reproduce the behavior:

1. Run command `nativeImage`
2. Watch the build log please.

**Expected behavior**

Successful build like this one: https://github.com/Kevin-Lee/whatsub/runs/6900296176?check_suite_focus=true#step:7:306
It's the build result when `sbt-native-image` `0.3.0` is used.

**Screenshots**

Failed build when `0.3.1` or `0.3.2` is used. (This screenshot was taken from the build with `0.3.2`).
![Screen Shot 2022-06-15 at 11 19 15 pm](https://user-images.githubusercontent.com/2307335/173836794-c2ac65a6-749c-42eb-85af-39620b5e235b.png)

**Installation:**

- Operating system: Windows
- Version: `windows-latest` from GitHub Actions

**Comment by eed3si9n** [comment]
I had to figure out how to build on Windows yesterday for sbt release. I don't think I saw the error message you're seeing but for me what fixed for me was downgrading to `windows-2019` image. See https://github.com/sbt/sbtn-dist/blob/1c92452932ec5a3693e242dc6136ed6c3fed75c7/.github/workflows/native.yml for the current YAML.

Also sent https://github.com/scalameta/sbt-native-image/pull/54 as fix.

**Comment by Kevin-Lee** [comment]
@eed3si9n Thanks Eugene. Sorry I found your answer only today.
Unfortunately, downgrading to `windows-2019` doesn't solve my issue.
With [these changes](https://github.com/Kevin-Lee/maven2sbt/pull/309/commits/1b69b301b5f2d62f5802bf1f3a791a6cc49d7dd5), the result is still [the same](https://github.com/Kevin-Lee/maven2sbt/runs/7974931519?check_suite_focus=true#step:7:342).

**Comment by 2m** [comment]
The path to `vcvars64.bat` changed a bit in Windows 2022:
```diff
-        "C:\Program Files (x86)\Microsoft Visual
-        Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
+        "C:\Program Files\Microsoft Visual
+        Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && sbt
```
